<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fieldofactivityannotations" nsURI="http://sdq.ipd.kit.edu/KAPSFieldofactivityannotations/1.0"
    nsPrefix="fieldofactivityannotations">
  <eClassifiers xsi:type="ecore:EClass" name="FieldOfActivityAnnotationRepository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="calibrationSpecification"
        eType="#//CalibrationSpecification" containment="true" eOpposite="#//CalibrationSpecification/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testSpecification" eType="#//TestSpecification"
        containment="true" eOpposite="#//TestSpecification/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="developmentSpecification"
        eType="#//DevelopmentSpecification" containment="true" eOpposite="#//DevelopmentSpecification/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="purchaseSpecification"
        eType="#//PurchaseSpecification" containment="true" eOpposite="#//PurchaseSpecification/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hmiSpecification" eType="#//HMISpecification"
        containment="true" eOpposite="#//HMISpecification/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ecadSpecification" eType="#//ECADSpecification"
        containment="true" eOpposite="#//ECADSpecification/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="documentationSpecification"
        eType="#//DocumentationSpecification" containment="true" eOpposite="#//DocumentationSpecification/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentSpecification"
        eType="#//ComponentSpecification" containment="true" eOpposite="#//ComponentSpecification/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="staffSpecification" eType="#//StaffSpecification"
        containment="true" eOpposite="#//StaffSpecification/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CalibrationSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//FieldOfActivityAnnotationRepository" eOpposite="#//FieldOfActivityAnnotationRepository/calibrationSpecification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//FieldOfActivityAnnotationRepository" eOpposite="#//FieldOfActivityAnnotationRepository/testSpecification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DevelopmentSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//FieldOfActivityAnnotationRepository" eOpposite="#//FieldOfActivityAnnotationRepository/developmentSpecification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PurchaseSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//FieldOfActivityAnnotationRepository" eOpposite="#//FieldOfActivityAnnotationRepository/purchaseSpecification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HMISpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//FieldOfActivityAnnotationRepository" eOpposite="#//FieldOfActivityAnnotationRepository/hmiSpecification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ECADSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//FieldOfActivityAnnotationRepository" eOpposite="#//FieldOfActivityAnnotationRepository/ecadSpecification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentationSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//FieldOfActivityAnnotationRepository" eOpposite="#//FieldOfActivityAnnotationRepository/documentationSpecification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//FieldOfActivityAnnotationRepository" eOpposite="#//FieldOfActivityAnnotationRepository/componentSpecification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StaffSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//FieldOfActivityAnnotationRepository" eOpposite="#//FieldOfActivityAnnotationRepository/staffSpecification"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="personList" lowerBound="1"
        eType="#//Base/PersonList" containment="true" eOpposite="#//Base/PersonList/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roleList" lowerBound="1"
        eType="#//Base/RoleList" containment="true" eOpposite="#//Base/RoleList/parent"/>
  </eClassifiers>
  <eSubpackages name="Base" nsURI="Base" nsPrefix="Base">
    <eClassifiers xsi:type="ecore:EClass" name="RoleList">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
          eType="#//StaffSpecification" eOpposite="#//StaffSpecification/roleList"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
          eType="#//Base/Role" eOpposite="#//Base/Role/parent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Role" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
          eType="#//Base/RoleList" eOpposite="#//Base/RoleList/roles"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="person" upperBound="-1"
          eType="#//Base/Person" eOpposite="#//Base/Person/roles"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PersonList">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
          eType="#//StaffSpecification" eOpposite="#//StaffSpecification/personList"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="persons" upperBound="-1"
          eType="#//Base/Person" containment="true" eOpposite="#//Base/Person/parent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Person">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
          eType="#//Base/PersonList" eOpposite="#//Base/PersonList/persons"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
          eType="#//Base/Role" eOpposite="#//Base/Role/person"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="File" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="TestCase" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Documentation" abstract="true"/>
  </eSubpackages>
  <eSubpackages name="Roles">
    <eClassifiers xsi:type="ecore:EClass" name="Engineer" eSuperTypes="#//Base/Role"/>
    <eClassifiers xsi:type="ecore:EClass" name="Purchaser" eSuperTypes="#//Base/Role"/>
    <eClassifiers xsi:type="ecore:EClass" name="Mechanic" eSuperTypes="#//Base/Role"/>
  </eSubpackages>
</ecore:EPackage>
