<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fieldofactivityannotations" nsURI="http://sdq.ipd.kit.edu/KAPSFieldofactivityannotations/1.0"
    nsPrefix="fieldofactivityannotations">
  <eClassifiers xsi:type="ecore:EClass" name="FieldOfActivityAnnotationRepository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="calibrationSpecification"
        eType="#//CalibrationSpecification" containment="true" eOpposite="#//CalibrationSpecification/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testSpecification" eType="#//TestSpecification"
        containment="true" eOpposite="#//TestSpecification/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="developmentSpecification"
        eType="#//DevelopmentSpecification" containment="true" eOpposite="#//DevelopmentSpecification/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="purchaseSpecification"
        eType="#//StockSpecification" containment="true" eOpposite="#//StockSpecification/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hmiSpecification" eType="#//HMISpecification"
        containment="true" eOpposite="#//HMISpecification/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ecadSpecification" eType="#//ECADSpecification"
        containment="true" eOpposite="#//ECADSpecification/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="documentationSpecification"
        eType="#//DocumentationSpecification" containment="true" eOpposite="#//DocumentationSpecification/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentSpecification"
        eType="#//ComponentSpecification" containment="true" eOpposite="#//ComponentSpecification/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="staffSpecification" eType="#//StaffSpecification"
        containment="true" eOpposite="#//StaffSpecification/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//FieldOfActivityAnnotationRepository" eOpposite="#//FieldOfActivityAnnotationRepository/testSpecification"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemTests" upperBound="-1"
        eType="#//SystemTest" containment="true" eOpposite="#//SystemTest/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StockSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//FieldOfActivityAnnotationRepository" eOpposite="#//FieldOfActivityAnnotationRepository/purchaseSpecification"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stockList" upperBound="-1"
        eType="#//StockList" containment="true" eOpposite="#//StockList/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HMISpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//FieldOfActivityAnnotationRepository" eOpposite="#//FieldOfActivityAnnotationRepository/hmiSpecification"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hmiConfiguration" upperBound="-1"
        eType="#//HMIConfiguration" eOpposite="#//HMIConfiguration/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HMIConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//HMISpecification" eOpposite="#//HMISpecification/hmiConfiguration"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="ecore:EClass ../../xPPU/model/xPPU.ecore#//ComponentRepository/Component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modules" upperBound="-1"
        eType="ecore:EClass ../../xPPU/model/xPPU.ecore#//ModuleRepository/Module"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaces" upperBound="-1"
        eType="ecore:EClass ../../xPPU/model/xPPU.ecore#//InterfaceRepository/Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="structures" upperBound="-1"
        eType="ecore:EClass ../../xPPU/model/xPPU.ecore#//StructureRepository/Structure"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ECADSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//FieldOfActivityAnnotationRepository" eOpposite="#//FieldOfActivityAnnotationRepository/ecadSpecification"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="ecore:EClass ../../xPPU/model/xPPU.ecore#//ComponentRepository/Component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modules" upperBound="-1"
        eType="ecore:EClass ../../xPPU/model/xPPU.ecore#//ModuleRepository/Module"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaces" upperBound="-1"
        eType="ecore:EClass ../../xPPU/model/xPPU.ecore#//InterfaceRepository/Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="structures" upperBound="-1"
        eType="ecore:EClass ../../xPPU/model/xPPU.ecore#//StructureRepository/Structure"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentationSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//FieldOfActivityAnnotationRepository" eOpposite="#//FieldOfActivityAnnotationRepository/documentationSpecification"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mainteneance" upperBound="-1"
        eType="#//MainteneanceDocumentation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instructions" upperBound="-1"
        eType="#//OperatorInstructions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trainingIntern" upperBound="-1"
        eType="#//TrainingDocIntern"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trainingExternal" upperBound="-1"
        eType="#//TrainingDocExternal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StaffSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//FieldOfActivityAnnotationRepository" eOpposite="#//FieldOfActivityAnnotationRepository/staffSpecification"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="personList" lowerBound="1"
        eType="#//PersonList" containment="true" eOpposite="#//PersonList/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roleList" lowerBound="1"
        eType="#//RoleList" containment="true" eOpposite="#//RoleList/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CalibrationSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//FieldOfActivityAnnotationRepository" eOpposite="#//FieldOfActivityAnnotationRepository/calibrationSpecification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DevelopmentSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//FieldOfActivityAnnotationRepository" eOpposite="#//FieldOfActivityAnnotationRepository/developmentSpecification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//FieldOfActivityAnnotationRepository" eOpposite="#//FieldOfActivityAnnotationRepository/componentSpecification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StockList" eSuperTypes="#//File">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//StockSpecification" eOpposite="#//StockSpecification/stockList"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="ecore:EClass ../../xPPU/model/xPPU.ecore#//ComponentRepository/Component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modules" upperBound="-1"
        eType="ecore:EClass ../../xPPU/model/xPPU.ecore#//ModuleRepository/Module"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaces" upperBound="-1"
        eType="ecore:EClass ../../xPPU/model/xPPU.ecore#//InterfaceRepository/Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="structures" upperBound="-1"
        eType="ecore:EClass ../../xPPU/model/xPPU.ecore#//StructureRepository/Structure"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoleList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//StaffSpecification" eOpposite="#//StaffSpecification/roleList"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="#//Role" eOpposite="#//Role/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//RoleList" eOpposite="#//RoleList/roles"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="person" upperBound="-1"
        eType="#//Person" eOpposite="#//Person/roles"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PersonList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//StaffSpecification" eOpposite="#//StaffSpecification/personList"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="persons" upperBound="-1"
        eType="#//Person" containment="true" eOpposite="#//Person/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//PersonList" eOpposite="#//PersonList/persons"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="#//Role" eOpposite="#//Role/person"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="File" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filename" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestCase" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Engineer" eSuperTypes="#//Role"/>
  <eClassifiers xsi:type="ecore:EClass" name="Purchaser" eSuperTypes="#//Role"/>
  <eClassifiers xsi:type="ecore:EClass" name="Mechanic" eSuperTypes="#//Role"/>
  <eClassifiers xsi:type="ecore:EClass" name="Documentation" eSuperTypes="#//File"/>
  <eClassifiers xsi:type="ecore:EClass" name="Drawing" eSuperTypes="#//File"/>
  <eClassifiers xsi:type="ecore:EClass" name="MainteneanceDocumentation" eSuperTypes="#//Documentation"/>
  <eClassifiers xsi:type="ecore:EClass" name="OperatorInstructions" eSuperTypes="#//Documentation"/>
  <eClassifiers xsi:type="ecore:EClass" name="TrainingDocIntern" eSuperTypes="#//Documentation"/>
  <eClassifiers xsi:type="ecore:EClass" name="TrainingDocExternal" eSuperTypes="#//Documentation"/>
  <eClassifiers xsi:type="ecore:EClass" name="SystemTest" eSuperTypes="#//TestCase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//TestSpecification" eOpposite="#//TestSpecification/systemTests"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemUnderTest" eType="ecore:EClass ../../xPPU/model/xPPU.ecore#//Plant"/>
  </eClassifiers>
</ecore:EPackage>
