<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="modificationmarks" nsURI="http://sdq.ipd.kit.edu/KAPSModificationmarks/1.0"
    nsPrefix="modificationmarks">
  <eClassifiers xsi:type="ecore:EClass" name="AbstractKAPSModificationRepository"
      abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//KAPSSeedModifications"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../edu.kit.ipd.sdq.kamp.model.modificationmarks/model/modificationmarks.ecore#//AbstractModificationRepository">
      <eTypeArguments eTypeParameter="#//AbstractKAPSModificationRepository/T"/>
      <eTypeArguments eClassifier="ecore:EClass ../../edu.kit.ipd.sdq.kamp.model.modificationmarks/model/modificationmarks.ecore#//ChangePropagationStep"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KAPSModificationRepository">
    <eGenericSuperTypes eClassifier="#//AbstractKAPSModificationRepository">
      <eTypeArguments eClassifier="#//KAPSSeedModifications"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KAPSSeedModifications" eSuperTypes="../../edu.kit.ipd.sdq.kamp.model.modificationmarks/model/modificationmarks.ecore#//AbstractSeedModifications">
    <eStructuralFeatures xsi:type="ecore:EReference" name="busBoxModifications" upperBound="-1"
        eType="#//ModifyBusBox" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensorModifications" upperBound="-1"
        eType="#//ModifySensor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="busMasterModifications"
        upperBound="-1" eType="#//ModifyBusMaster" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="busSlaveModifications"
        upperBound="-1" eType="#//ModifyBusSlave" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="microswitchModuleModifications"
        upperBound="-1" eType="#//ModifyMicroSwitchModule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChangePropagationDueToHardwareChange"
      eSuperTypes="../../edu.kit.ipd.sdq.kamp.model.modificationmarks/model/modificationmarks.ecore#//ChangePropagationStep">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensorModifications" upperBound="-1"
        eType="#//ModifySensor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signalinterfaceModifications"
        upperBound="-1" eType="#//ModifySignalinterface" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="physicalConnectionModifications"
        upperBound="-1" eType="#//ModifyPhysicalConnection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="microSwitchModuleModifications"
        upperBound="-1" eType="#//ModifyMicroSwitchModule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="busBoxModifications" upperBound="-1"
        eType="#//ModifyBusBox" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="busMasterModifications"
        upperBound="-1" eType="#//ModifyBusMaster" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="busSlaveModifications"
        upperBound="-1" eType="#//ModifyBusSlave" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="busCableModifications"
        upperBound="-1" eType="#//ModifyBusCable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaceModifications"
        upperBound="-1" containment="true">
      <eGenericType eClassifier="#//ModifyInterface">
        <eTypeArguments eClassifier="ecore:EClass ../../xPPU/model/xPPU.ecore#//InterfaceRepository/Interface"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentModifications"
        upperBound="-1" containment="true">
      <eGenericType eClassifier="#//ModifyComponent">
        <eTypeArguments eClassifier="ecore:EClass ../../xPPU/model/xPPU.ecore#//ComponentRepository/Component"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="structureModifications"
        upperBound="-1" containment="true">
      <eGenericType eClassifier="#//ModifyStructure">
        <eTypeArguments eClassifier="ecore:EClass ../../xPPU/model/xPPU.ecore#//StructureRepository/Structure"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModifyComponent">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass ../../xPPU/model/xPPU.ecore#//ComponentRepository/Component"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../edu.kit.ipd.sdq.kamp.model.modificationmarks/model/modificationmarks.ecore#//AbstractModification">
      <eTypeArguments eTypeParameter="#//ModifyComponent/T"/>
      <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModifyModule">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass ../../xPPU/model/xPPU.ecore#//ModuleRepository/Module"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../edu.kit.ipd.sdq.kamp.model.modificationmarks/model/modificationmarks.ecore#//AbstractModification">
      <eTypeArguments eTypeParameter="#//ModifyModule/T"/>
      <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModifyStructure">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass ../../xPPU/model/xPPU.ecore#//StructureRepository/Structure"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../edu.kit.ipd.sdq.kamp.model.modificationmarks/model/modificationmarks.ecore#//AbstractModification">
      <eTypeArguments eTypeParameter="#//ModifyStructure/T"/>
      <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModifyInterface">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass ../../xPPU/model/xPPU.ecore#//InterfaceRepository/Interface"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../edu.kit.ipd.sdq.kamp.model.modificationmarks/model/modificationmarks.ecore#//AbstractModification">
      <eTypeArguments eTypeParameter="#//ModifyInterface/T"/>
      <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModifyPowerSupply">
    <eGenericSuperTypes eClassifier="#//ModifyComponent">
      <eTypeArguments eClassifier="ecore:EClass ../../xPPU/model/xPPU.ecore#//ComponentRepository/PowerSupply"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//ModifyInterface">
      <eTypeArguments eClassifier="ecore:EClass ../../xPPU/model/xPPU.ecore#//ComponentRepository/PowerSupply"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModifySignalinterface">
    <eGenericSuperTypes eClassifier="#//ModifyInterface">
      <eTypeArguments eClassifier="ecore:EClass ../../xPPU/model/xPPU.ecore#//InterfaceRepository/SignalInterface"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModifyPhysicalConnection">
    <eGenericSuperTypes eClassifier="#//ModifyInterface">
      <eTypeArguments eClassifier="ecore:EClass ../../xPPU/model/xPPU.ecore#//InterfaceRepository/PhysicalConnection"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModifyMicroSwitchModule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isReplaced" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eGenericSuperTypes eClassifier="#//ModifyComponent">
      <eTypeArguments eClassifier="ecore:EClass ../../xPPU/model/xPPU.ecore#//ComponentRepository/MicroswitchModule"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModifyBusBox">
    <eGenericSuperTypes eClassifier="#//ModifyComponent">
      <eTypeArguments eClassifier="ecore:EClass ../../xPPU/model/xPPU.ecore#//BusComponents/BusBox"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModifyBusMaster">
    <eGenericSuperTypes eClassifier="#//ModifyComponent">
      <eTypeArguments eClassifier="ecore:EClass ../../xPPU/model/xPPU.ecore#//BusComponents/BusMaster"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModifyBusSlave">
    <eGenericSuperTypes eClassifier="#//ModifyComponent">
      <eTypeArguments eClassifier="ecore:EClass ../../xPPU/model/xPPU.ecore#//BusComponents/BusSlave"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModifyBusCable">
    <eGenericSuperTypes eClassifier="#//ModifyComponent">
      <eTypeArguments eClassifier="ecore:EClass ../../xPPU/model/xPPU.ecore#//BusComponents/BusCable"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModifySensor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modifySignalInterfaces"
        upperBound="-1" eType="ecore:EClass ../../xPPU/model/xPPU.ecore#//InterfaceRepository/SignalInterface"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modifyPhysicalConnections"
        upperBound="-1" eType="ecore:EClass ../../xPPU/model/xPPU.ecore#//InterfaceRepository/PhysicalConnection"
        containment="true"/>
    <eGenericSuperTypes eClassifier="#//ModifyComponent">
      <eTypeArguments eClassifier="ecore:EClass ../../xPPU/model/xPPU.ecore#//ComponentRepository/Sensor"/>
    </eGenericSuperTypes>
  </eClassifiers>
</ecore:EPackage>
